const menu = [
    {
      category: "Appetizers",
      items: [
        { name: "Coxinha", description: "Chicken croquettes", price: 5.0 },
        { name: "Pão de Queijo", description: "Cheese bread rolls", price: 4.0 },
        { name: "Bolinho de Bacalhau", description: "Codfish cakes", price: 6.0 },
        { name: "Kibe", description: "Spiced bulgur and meat croquettes", price: 5.5 },
        { name: "Pastéis", description: "Fried pastries with assorted fillings", price: 4.5 },
        { name: "Acarajé", description: "Black-eyed pea fritters with shrimp", price: 5.5 },
        { name: "Empada", description: "Mini pies with various fillings", price: 4.5 },
        { name: "Esfiha", description: "Middle Eastern meat pastries", price: 5.0 },
        { name: "Tapioca", description: "Tapioca crepes with cheese", price: 4.0 },
        { name: "Bolinho de Aipim", description: "Cassava balls with cheese", price: 5.0 },
        { name: "Mandioca Frita", description: "Fried cassava sticks", price: 4.5 },
        { name: "Polenta Frita", description: "Fried polenta sticks", price: 4.0 },
        { name: "Salpicão", description: "Chicken salad with mayonnaise", price: 5.5 },
        { name: "Bolinho de Carne", description: "Meatballs", price: 5.0 },
        { name: "Caldinho de Feijão", description: "Black bean soup", price: 4.0 },
        { name: "Bolinho de Arroz", description: "Rice balls", price: 4.5 },
        { name: "Tábua de Frios", description: "Cold cuts and cheese platter", price: 6.5 },
        { name: "Linguiça Frita", description: "Fried sausage", price: 5.0 },
        { name: "Pão com Alho", description: "Garlic bread", price: 3.5 },
        { name: "Ovo de Codorna", description: "Quail eggs with herbs", price: 4.5 },
        { name: "Torradas com Patê", description: "Toasts with pâté", price: 4.0 },
        { name: "Bolinhos de Queijo", description: "Cheese balls", price: 5.0 },
        { name: "Carne de Sol com Mandioca", description: "Sun-dried meat with cassava", price: 6.0 },
        { name: "Calabresa Acebolada", description: "Sausage with onions", price: 5.0 },
        { name: "Espetinho de Frango", description: "Chicken skewers", price: 4.5 },
        { name: "Espetinho de Camarão", description: "Shrimp skewers", price: 6.0 },
        { name: "Camarão Alho e Óleo", description: "Garlic and oil shrimp", price: 6.0 },
        { name: "Moela Acebolada", description: "Gizzards with onions", price: 4.5 },
        { name: "Frango à Passarinho", description: "Fried chicken bites", price: 5.5 },
        { name: "Azeitonas Temperadas", description: "Seasoned olives", price: 3.5 },
        { name: "Salada de Palmito", description: "Hearts of palm salad", price: 5.5 },
        { name: "Ceviche", description: "Brazilian style ceviche", price: 6.5 },
        { name: "Batata Frita", description: "French fries", price: 3.5 },
        { name: "Batata Rústica", description: "Rustic potatoes", price: 4.0 },
        { name: "Canapé de Salmão", description: "Salmon canapés", price: 6.0 },
        { name: "Carpaccio de Carne", description: "Beef carpaccio", price: 6.5 },
        { name: "Casquinha de Siri", description: "Stuffed crab shells", price: 5.5 },
        { name: "Quibe Cru", description: "Raw kibbeh", price: 6.0 },
        { name: "Sanduíche Natural", description: "Natural sandwich", price: 4.0 },
      ],
    },
    {
      category: "Main Courses",
      items: [
        { name: "Feijoada", description: "Brazilian black bean stew with pork", price: 12.0 },
        { name: "Picanha", description: "Grilled rump steak", price: 15.0 },
        { name: "Moqueca", description: "Brazilian fish stew with coconut milk", price: 14.0 },
        { name: "Coxinha de Frango", description: "Chicken stew with manioc", price: 13.0 },
        { name: "Churrasco", description: "Brazilian barbecue assortment", price: 16.0 },
        { name: "Bobo de Camarão", description: "Shrimp in a manioc cream sauce", price: 14.5 },
        { name: "Vatapá", description: "Seafood and coconut milk stew", price: 13.0 },
        { name: "Acarajé", description: "Fried black-eyed pea ball with shrimp", price: 11.0 },
        { name: "Escondidinho", description: "Cassava casserole with meat", price: 12.0 },
        { name: "Galinhada", description: "Brazilian chicken and rice", price: 13.5 },
        { name: "Baião de Dois", description: "Rice and beans with meat", price: 12.5 },
        { name: "Frango com Quiabo", description: "Chicken with okra", price: 11.5 },
        { name: "Rabada", description: "Oxtail stew", price: 14.0 },
        { name: "Costela no Bafo", description: "Steamed ribs", price: 15.0 },
        { name: "Tutu de Feijão", description: "Bean paste with sausage and bacon", price: 11.0 },
        { name: "Feijão Tropeiro", description: "Beans with sausage and collard greens", price: 12.5 },
        { name: "Arroz de Pato", description: "Duck rice", price: 14.0 },
        { name: "Caldeirada", description: "Seafood stew", price: 14.5 },
        { name: "Peixada", description: "Fish stew", price: 13.5 },
        { name: "Vaca Atolada", description: "Beef ribs with cassava", price: 12.0 },
        { name: "Bife à Cavalo", description: "Steak with fried eggs", price: 11.0 },
        { name: "Carne Seca com Abóbora", description: "Sun-dried beef with pumpkin", price: 12.0 },
        { name: "Arroz com Pequi", description: "Rice with pequi fruit", price: 10.5 },
        { name: "Pato no Tucupi", description: "Duck in tucupi sauce", price: 15.0 },
        { name: "Acarajé com Vatapá", description: "Acarajé with vatapá", price: 11.0 },
        { name: "Caldo Verde", description: "Green broth with sausage and potatoes", price: 10.0 },
        { name: "Lasanha de Berinjela", description: "Eggplant lasagna", price: 12.5 },
        { name: "Moqueca de Banana", description: "Banana moqueca", price: 11.0 },
        { name: "Arroz Carreteiro", description: "Wagoner's rice with meat", price: 12.0 },
        { name: "Chester Recheado", description: "Stuffed chester", price: 14.0 },
        { name: "Carne de Sol com Queijo", description: "Sun-dried meat with cheese", price: 13.0 },
        { name: "Picanha na Chapa", description: "Grilled picanha", price: 15.0 },
        { name: "Tilápia Grelhada", description: "Grilled tilapia", price: 13.0 },
        { name: "Frango ao Molho Pardo", description: "Chicken in brown sauce", price: 12.5 },
        { name: "Sarapatel", description: "Offal stew", price: 11.0 },
        { name: "Frango Assado", description: "Roast chicken", price: 13.0 },
        { name: "Camarão na Moranga", description: "Pumpkin stuffed with shrimp", price: 15.0 },
        { name: "Cordeiro Assado", description: "Roast lamb", price: 16.0 },
        { name: "Rocambole de Carne", description: "Meat roulade", price: 12.0 },
      ],
    },
    {
      category: "Desserts",
      items: [
        { name: "Brigadeiro", description: "Chocolate truffles", price: 3.0 },
        { name: "Quindim", description: "Coconut custard", price: 4.0 },
        { name: "Pudim", description: "Brazilian caramel flan", price: 4.5 },
        { name: "Bolo de Rolo", description: "Rolled sponge cake with guava paste", price: 5.0 },
        { name: "Canjica", description: "Sweet corn pudding", price: 4.5 },
        { name: "Beijinho", description: "Coconut balls", price: 3.0 },
        { name: "Romeu e Julieta", description: "Guava paste with cheese", price: 4.0 },
        { name: "Mousse de Maracujá", description: "Passion fruit mousse", price: 4.0 },
        { name: "Curau", description: "Corn pudding", price: 3.5 },
        { name: "Pavê", description: "Layered dessert with biscuits and cream", price: 4.5 },
        { name: "Cocada", description: "Coconut candy", price: 3.0 },
        { name: "Manjar Branco", description: "Coconut blancmange", price: 4.5 },
        { name: "Rabanada", description: "Brazilian French toast", price: 3.5 },
        { name: "Paçoca", description: "Peanut candy", price: 3.0 },
        { name: "Torta de Limão", description: "Lemon tart", price: 4.0 },
        { name: "Brigadeirão", description: "Chocolate flan", price: 5.0 },
        { name: "Quindão", description: "Large quindim", price: 5.0 },
        { name: "Arroz Doce", description: "Rice pudding", price: 3.5 },
        { name: "Bolo de Cenoura", description: "Carrot cake with chocolate", price: 4.0 },
        { name: "Banana Frita", description: "Fried banana", price: 3.0 },
        { name: "Sagu", description: "Tapioca pearls in wine", price: 3.5 },
        { name: "Doce de Leite", description: "Milk caramel", price: 3.5 },
        { name: "Pé de Moleque", description: "Peanut brittle", price: 3.0 },
        { name: "Tapioca Pudding", description: "Tapioca and coconut pudding", price: 4.0 },
        { name: "Gelatina Colorida", description: "Rainbow jelly", price: 3.0 },
        { name: "Biscoito de Polvilho", description: "Cassava starch biscuits", price: 2.5 },
        { name: "Bananada", description: "Banana candy", price: 3.0 },
        { name: "Ambrosia", description: "Egg and milk dessert", price: 4.5 },
        { name: "Torta Holandesa", description: "Dutch pie", price: 4.5 },
        { name: "Torta de Maçã", description: "Apple pie", price: 4.5 },
        { name: "Bolo de Milho", description: "Corn cake", price: 3.5 },
        { name: "Pamonha", description: "Corn pudding", price: 3.0 },
        { name: "Bolo de Fubá", description: "Cornmeal cake", price: 3.5 },
        { name: "Torta de Morango", description: "Strawberry tart", price: 5.0 },
        { name: "Trufa de Chocolate", description: "Chocolate truffle", price: 3.5 },
        { name: "Mousse de Chocolate", description: "Chocolate mousse", price: 4.0 },
        { name: "Sorvete de Tapioca", description: "Tapioca ice cream", price: 4.5 },
        { name: "Docinho de Abóbora", description: "Pumpkin candy", price: 3.0 },
      ],
    },
    {
      category: "Drinks",
      items: [
        { name: "Caipirinha", description: "Brazilian lime cocktail", price: 6.0 },
        { name: "Guaraná", description: "Brazilian guaraná soda", price: 3.5 },
        { name: "Cachaça", description: "Brazilian sugarcane spirit", price: 5.0 },
        { name: "Açaí Smoothie", description: "Smoothie made with açaí berries", price: 4.5 },
        { name: "Coconut Water", description: "Fresh coconut water", price: 3.0 },
        { name: "Batida de Coco", description: "Coconut cocktail", price: 5.5 },
        { name: "Caldo de Cana", description: "Sugarcane juice", price: 3.0 },
        { name: "Suco de Maracujá", description: "Passion fruit juice", price: 3.0 },
        { name: "Suco de Goiaba", description: "Guava juice", price: 3.0 },
        { name: "Suco de Acerola", description: "Acerola juice", price: 3.0 },
        { name: "Mate Gelado", description: "Iced mate tea", price: 3.0 },
        { name: "Vitamina de Abacate", description: "Avocado smoothie", price: 3.5 },
        { name: "Cajuína", description: "Cashew juice", price: 3.5 },
        { name: "Limonada Suíça", description: "Swiss lemonade", price: 3.0 },
        { name: "Caipiroska", description: "Vodka-based caipirinha", price: 6.0 },
        { name: "Rabo de Galo", description: "Cachaça with vermouth", price: 5.5 },
        { name: "Quentão", description: "Hot spiced wine", price: 4.0 },
        { name: "Cerveja", description: "Beer", price: 4.0 },
        { name: "Vinho Brasileiro", description: "Brazilian wine", price: 5.0 },
        { name: "Pinga com Mel", description: "Cachaça with honey", price: 4.5 },
        { name: "Licor de Jabuticaba", description: "Jabuticaba liqueur", price: 5.5 },
        { name: "Chá de Hibisco", description: "Hibiscus tea", price: 3.0 },
        { name: "Chá Mate", description: "Mate tea", price: 2.5 },
        { name: "Guaraná Jesus", description: "Guaraná soda from Maranhão", price: 3.5 },
        { name: "Suco de Graviola", description: "Soursop juice", price: 3.0 },
        { name: "Suco de Cupuaçu", description: "Cupuaçu juice", price: 3.0 },
        { name: "Refrigerante de Uva", description: "Grape soda", price: 2.5 },
        { name: "Refrigerante de Laranja", description: "Orange soda", price: 2.5 },
        { name: "Água de Coco", description: "Coconut water", price: 3.0 },
        { name: "Água Mineral", description: "Mineral water", price: 2.0 },
        { name: "Chimarrão", description: "Hot mate tea", price: 3.0 },
        { name: "Tubaína", description: "Brazilian soda", price: 3.0 },
        { name: "Xarope de Groselha", description: "Redcurrant syrup drink", price: 3.0 },
        { name: "Chocolate Quente", description: "Hot chocolate", price: 3.5 },
        { name: "Suco de Acerola com Laranja", description: "Acerola and orange juice", price: 3.5 },
        { name: "Café Brasileiro", description: "Brazilian coffee", price: 2.0 },
        { name: "Smoothie de Banana e Morango", description: "Banana and strawberry smoothie", price: 3.5 },
        { name: "Vitamina de Mamão", description: "Papaya smoothie", price: 3.5 },
        { name: "Refrigerante de Limão", description: "Lemon soda", price: 2.5 },
        { name: "Ponche de Frutas", description: "Fruit punch", price: 3.0 },
      ],
    },
    {
      category: "20 menu",
      items: [
        { name: "Coxinha", description: "Chicken croquettes", price: 3.0 },
        { name: "Feijoada", description: "Brazilian black bean stew with pork", price: 11.0 },
        { name: "Brigadeiro", description: "Chocolate truffles", price: 3.0 },
        { name: "Guaraná", description: "Brazilian guaraná soda", price: 3.0 },
        { name: "Pão de Queijo", description: "Cheese bread rolls", price: 3.0 },
        { name: "Picanha", description: "Grilled rump steak", price: 11.0 },
        { name: "Quindim", description: "Coconut custard", price: 3.0 },
        { name: "Cachaça", description: "Brazilian sugarcane spirit", price: 3.0 },
        { name: "Kibe", description: "Spiced bulgur and meat croquettes", price: 3.0 },
        { name: "Moqueca", description: "Brazilian fish stew with coconut milk", price: 11.0 },
        { name: "Pudim", description: "Brazilian caramel flan", price: 3.0 },
        { name: "Açaí Smoothie", description: "Smoothie made with açaí berries", price: 3.0 },
        { name: "Pastéis", description: "Fried pastries with assorted fillings", price: 3.0 },
        { name: "Churrasco", description: "Brazilian barbecue assortment", price: 11.0 },
        { name: "Bolo de Rolo", description: "Rolled sponge cake with guava paste", price: 3.0 },
        { name: "Coconut Water", description: "Fresh coconut water", price: 3.0 },
        { name: "Bolinho de Bacalhau", description: "Codfish cakes", price: 3.0 },
        { name: "Coxinha de Frango", description: "Chicken stew with manioc", price: 11.0 },
        { name: "Canjica", description: "Sweet corn pudding", price: 3.0 },
        { name: "Batida de Coco", description: "Coconut cocktail", price: 3.0 },
        { name: "Empada", description: "Mini pies with various fillings", price: 3.0 },
        { name: "Bobo de Camarão", description: "Shrimp in a manioc cream sauce", price: 11.0 },
        { name: "Beijinho", description: "Coconut balls", price: 3.0 },
        { name: "Caldo de Cana", description: "Sugarcane juice", price: 3.0 },
        { name: "Esfiha", description: "Middle Eastern meat pastries", price: 3.0 },
        { name: "Galinhada", description: "Brazilian chicken and rice", price: 11.0 },
        { name: "Romeu e Julieta", description: "Guava paste with cheese", price: 3.0 },
        { name: "Suco de Maracujá", description: "Passion fruit juice", price: 3.0 },
        { name: "Tapioca", description: "Tapioca crepes with cheese", price: 3.0 },
        { name: "Frango com Quiabo", description: "Chicken with okra", price: 11.0 },
        { name: "Mousse de Maracujá", description: "Passion fruit mousse", price: 3.0 },
        { name: "Suco de Goiaba", description: "Guava juice", price: 3.0 },
        { name: "Bolinho de Aipim", description: "Cassava balls with cheese", price: 3.0 },
        { name: "Carne de Sol com Mandioca", description: "Sun-dried meat with cassava", price: 11.0 },
        { name: "Curau", description: "Corn pudding", price: 3.0 },
        { name: "Suco de Acerola", description: "Acerola juice", price: 3.0 },
        { name: "Salpicão", description: "Chicken salad with mayonnaise", price: 3.0 },
        { name: "Rabada", description: "Oxtail stew", price: 11.0 },
        { name: "Pavê", description: "Layered dessert with biscuits and cream", price: 3.0 },
        { name: "Mate Gelado", description: "Iced mate tea", price: 3.0 },
        { name: "Biscoito de Polvilho", description: "Cassava starch biscuits", price: 3.0 },
        { name: "Manjar Branco", description: "Coconut blancmange", price: 3.0 },
        { name: "Linguiça Frita", description: "Fried sausage", price: 3.0 },
        { name: "Costela no Bafo", description: "Steamed ribs", price: 11.0 },
        { name: "Rabanada", description: "Brazilian French toast", price: 3.0 },
        { name: "Vitamina de Abacate", description: "Avocado smoothie", price: 3.0 },
        { name: "Tábua de Frios", description: "Cold cuts and cheese platter", price: 3.0 },
        { name: "Tutu de Feijão", description: "Bean paste with sausage and bacon", price: 11.0 },
        { name: "Paçoca", description: "Peanut candy", price: 3.0 },
        { name: "Cajuína", description: "Cashew juice", price: 3.0 },
        { name: "Pão com Alho", description: "Garlic bread", price: 3.0 },
        { name: "Feijão Tropeiro", description: "Beans with sausage and collard greens", price: 11.0 },
        { name: "Torta de Limão", description: "Lemon tart", price: 3.0 },
        { name: "Limonada Suíça", description: "Swiss lemonade", price: 3.0 },
        { name: "Ovo de Codorna", description: "Quail eggs with herbs", price: 3.0 },
        { name: "Caldeirada", description: "Seafood stew", price: 11.0 },
        { name: "Brigadeirão", description: "Chocolate flan", price: 3.0 },
        { name: "Caipiroska", description: "Vodka-based caipirinha", price: 3.0 },
        { name: "Bolinhos de Queijo", description: "Cheese balls", price: 3.0 },
        { name: "Peixada", description: "Fish stew", price: 11.0 },
        { name: "Quindão", description: "Large quindim", price: 3.0 },
        { name: "Rabo de Galo", description: "Cachaça with vermouth", price: 3.0 },
        { name: "Mandioca Frita", description: "Fried cassava sticks", price: 3.0 },
        { name: "Vaca Atolada", description: "Beef ribs with cassava", price: 11.0 },
        { name: "Arroz Doce", description: "Rice pudding", price: 3.0 },
        { name: "Quentão", description: "Hot spiced wine", price: 3.0 },
        { name: "Polenta Frita", description: "Fried polenta sticks", price: 3.0 },
        { name: "Bife à Cavalo", description: "Steak with fried eggs", price: 11.0 },
        { name: "Bolo de Cenoura", description: "Carrot cake with chocolate", price: 3.0 },
        { name: "Cerveja", description: "Beer", price: 3.0 },
        { name: "Bolinho de Carne", description: "Meatballs", price: 3.0 },
        { name: "Carne Seca com Abóbora", description: "Sun-dried beef with pumpkin", price: 11.0 },
        { name: "Banana Frita", description: "Fried banana", price: 3.0 },
        { name: "Vinho Brasileiro", description: "Brazilian wine", price: 3.0 },
        { name: "Caldinho de Feijão", description: "Black bean soup", price: 3.0 },
        { name: "Arroz com Pequi", description: "Rice with pequi fruit", price: 11.0 },
        { name: "Sagu", description: "Tapioca pearls in wine", price: 3.0 },
        { name: "Pinga com Mel", description: "Cachaça with honey", price: 3.0 },
        { name: "Tainha Assada", description: "Grilled mullet fish", price: 11.0 },
        { name: "Doce de Leite", description: "Milk caramel", price: 3.0 },
        { name: "Licor de Jabuticaba", description: "Jabuticaba liqueur", price: 3.0 },
        { name: "Aipim Frito", description: "Fried manioc sticks", price: 3.0 },
        { name: "Costela de Porco", description: "Pork ribs", price: 11.0 },
        { name: "Pé de Moleque", description: "Peanut brittle", price: 3.0 },
        { name: "Chá de Hibisco", description: "Hibiscus tea", price: 3.0 },
        { name: "Macaxeira Frita", description: "Fried cassava sticks", price: 3.0 },
        { name: "Cuscuz Paulista", description: "Savory corn and vegetable cake", price: 11.0 },
        { name: "Tapioca Pudding", description: "Tapioca and coconut pudding", price: 3.0 },
        { name: "Chá Mate", description: "Mate tea", price: 3.0 },
        { name: "Salame", description: "Brazilian salami", price: 3.0 },
        { name: "Bolo de Milho", description: "Corn cake", price: 3.0 },
        { name: "Guaraná Jesus", description: "Guaraná soda from Maranhão", price: 3.0 },
        { name: "Mousse de Chocolate", description: "Chocolate mousse", price: 3.0 },
        { name: "Suco de Graviola", description: "Soursop juice", price: 3.0 },
        { name: "Sorvete de Tapioca", description: "Tapioca ice cream", price: 3.0 },
        { name: "Docinho de Abóbora", description: "Pumpkin candy", price: 3.0 },
        { name: "Suco de Cupuaçu", description: "Cupuaçu juice", price: 3.0 },
        { name: "Refrigerante de Uva", description: "Grape soda", price: 3.0 },
        { name: "Refrigerante de Laranja", description: "Orange soda", price: 3.0 },
        { name: "Torresmo", description: "Pork cracklings", price: 3.0 },
        { name: "Farofa", description: "Toasted cassava flour mixture", price: 3.0 },
        { name: "Refrigerante de Limão", description: "Lemon soda", price: 3.0 },
        { name: "Sorvete de Açaí", description: "Açaí ice cream", price: 3.0 },
        { name: "Água de Coco", description: "Coconut water", price: 3.0 },
        { name: "Ponche de Frutas", description: "Fruit punch", price: 3.0 },
        { name: "Água Mineral", description: "Mineral water", price: 3.0 },
        { name: "Suco de Acerola com Laranja", description: "Acerola and orange juice", price: 3.0 },
        { name: "Café Brasileiro", description: "Brazilian coffee", price: 3.0 },
        { name: "Chimarrão", description: "Hot mate tea", price: 3.0 },
        { name: "Xarope de Groselha", description: "Redcurrant syrup drink", price: 3.0 },
        { name: "Smoothie de Banana e Morango", description: "Banana and strawberry smoothie", price: 3.0 },
        { name: "Chocolate Quente", description: "Hot chocolate", price: 3.0 },
        { name: "Vitamina de Mamão", description: "Papaya smoothie", price: 3.0 },
        { name: "Tubaína", description: "Brazilian soda", price: 3.0 },
      ],
    },
  ];  
  
  const menuContainer = document.querySelector("#menu");
  
  menuItems.forEach(category => {
    const categoryElement = document.createElement("div");
    categoryElement.classList.add("category");
  
    const categoryTitle = document.createElement("h2");
    categoryTitle.textContent = category.category;
    categoryElement.appendChild(categoryTitle);
  
    category.items.forEach(item => {
      const itemElement = document.createElement("div");
      itemElement.classList.add("menu-item");
  
      const itemName = document.createElement("h3");
      itemName.textContent = item.name;
      itemElement.appendChild(itemName);
  
      const itemDescription = document.createElement("p");
      itemDescription.textContent = item.description;
      itemElement.appendChild(itemDescription);
  
      const itemPrice = document.createElement("span");
      itemPrice.textContent = `$${item.price.toFixed(2)}`;
      itemElement.appendChild(itemPrice);
  
      categoryElement.appendChild(itemElement);
    });
  
    menuContainer.appendChild(categoryElement);
  });
  